### ISSUE TITLE
Working example of DynamoDb

### ISSUE THREAD

**Issue by sharmmoh1983** [reactiverse/aws-sdk#20]
Hi 
I am trying to create vertx microservice accessing DynamoDb in the backend

Kindly provide some working example for the same

Also is this vertx client production ready?

**Comment by aesteve** [comment]
Would [this](https://reactiverse.io/aws-sdk/) be ok ?

**Comment by vietj** [comment]
@sharmmoh1983 we will do soon a first release, it's  based on AWS-SDK and Vert.x which are production ready, there might be bug in this project and they will be fixed when reported with frequent releases
