### ISSUE TITLE
Add this project to vertx-awesome

### ISSUE THREAD

**Issue by vietj** [reactiverse/aws-sdk#24]

**Comment by aesteve** [comment]
As soon as artifacts are published to Maven Central I'll do it, sure :)

**Comment by vietj** [comment]
yay, I know what you mean :)

**Comment by vietj** [comment]
the fact it is gradle might be a problem due to my limited knowledge though, I'll try hard

**Comment by vietj** [comment]
I mean I would need to setup a release process using maven and then translate it to gradle

**Comment by aesteve** [comment]
https://github.com/vert-x3/vertx-awesome/pull/156

**Comment by aesteve** [comment]
Done.
Thanks @vietj
