### ISSUE TITLE
Project not available through Maven

### ISSUE THREAD

**Issue by davidzzzzz** [reactiverse/aws-sdk#32]
Hi folks! We'd love to use this project, but when we follow the readme to import this project in gradle, we're not able to resolve the artifact. 

Would it be possible to start publishing releases for this project to a maven repo?

**Comment by aesteve** [comment]
We're looking at it.

We're investigating different alternatives for signing/publishing artifacts.

Sorry for the inconvenience.

**Comment by davidzzzzz** [comment]
No worries at all!

**Comment by vietj** [comment]
version 0.0.3 has been released in Maven Central, it should be synchronized soon

**Comment by vietj** [comment]
It should actually be 0.3.0

**Comment by chris-brace** [comment]
it seems like only 0.3.0 ever got pushed to maven! i can't seem to find 0.6.0 anywhere. Am i looking in the wrong place? https://search.maven.org/search?q=a:vertx-aws-sdk

**Comment by aesteve** [comment]
https://search.maven.org/search?q=a:aws-sdk

You'll find every a aivalable version here

**Comment by chris-brace** [comment]
Thank you! I made a pr to update the README.md https://github.com/reactiverse/aws-sdk/pull/48
