### ISSUE TITLE
Kotlin extension methods

### ISSUE THREAD

**Issue by aesteve** [reactiverse/aws-sdk#33]
@wem said:

> Are you interested in Kotlin extensions for this library in a separate sub-lib like aws-sdk-lang-kotlin? I think about a collection of AWS SDK extensions with the Await approach, like most of the other Vert.x libraries have. I ask because it would be some work :)

I personally don't have enough knowledge in Kotlin koroutines to manage such a set of extension methods.

I think reactiverse maintainers should  probably be consulted and give their opinion. But in the meantime, maybe @wem you could set the foundations of such a project in a personal repository, so that we can get a glimpse at what it looks like.

**Comment by wem** [comment]
@aesteve 
In a first instance, i will do it for a single AWS async client and open a PR, so we can discuss this here. My offer would be to maintain this extension, as i expect some initial effort but not that the AWS SDK API will change that much within a major release.

But please give me some time (maybe around 2 weeks) as i'm currently a little bit busy.

Would that be an option for you?

**Comment by aesteve** [comment]
Not a matter of time, take all the time you need :)

Just a matter of responabilities / organization.

I think it'd be easier to have it in your own repo, your own experiment, your own organization, then just comment this issue to show results.

Once it's OK, given many parameters as the amount of code needed, etc. etc. We can discuss whether it's a good candidate for integration or not.

Thanks a lot for the proposal though, curious to see what it'd look like!

**Comment by wem** [comment]
I think that could be closed, as the most relevant extension functions are already provided by Jetbrains for CompletableFuture. I personally don't see any todo here, especially as since Vert.x 4 the "await" function variants got replaced (deprecated) by the consequent move to Futures, and the suspendable corresponding await extension function.
