### ISSUE TITLE
s3: stream downloaded bytes?

### ISSUE THREAD

**Issue by st-h** [reactiverse/aws-sdk#35]
Is it possible to stream/pump the bytes received from s3 to a vertx stream (like pushing the received bytes to a vertx HttpServerResponse). From looking at the code and tests, I think we would need a streaming implementation of AsyncResponseTransformer.toBytes, which would pump bytes as soon as they are available.
Or did I miss something and this already is possible?

**Comment by aesteve** [comment]
Hello.

I've read the `AsyncResponseTransformer.toBytes` source code, and it looks it relies on reactive streams `Publisher`/`Subscriber`

https://github.com/aws/aws-sdk-java-v2/blob/master/core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/async/ByteArrayAsyncResponseTransformer.java#L69

We could experiment on either it's better to implement `AsyncResponseTransformer` directly (and not adding a dependency to rxJava) or use vertx reactive streams "bridge" to implement it with less code, but introduce a new dependency.

Good question, thanks.

I need to experiment and give this a try.

**Comment by aesteve** [comment]
I tried to implement it here: https://github.com/reactiverse/aws-sdk/pull/36/files

**Comment by st-h** [comment]
@aesteve thank you for looking into this. I have been checking out your PR locally and tried to use it, however I have run into some issues (which probably might be related to my current lack of experience with reactive streams)

I am using the new transformer like this:

```
VertxAsyncResponseTransformer transformer = new VertxAsyncResponseTransformer<>(httpServerResponse);
final CompletableFuture s3Future = s3.getObject(
                GetObjectRequest.builder()
                        .bucket(bucket)
                        .key(key)
                        .range(range)
                        .build(),
                transformer);

s3Future.thenAccept({ HttpServerResponse response ->
              // try to set response headers etc....
})
```

I was having issues with seeing empty responses from vertx and being unable to set any headers:

As for the first issue, I have been trying to add some debug logging to the `WriteStreamSubscriber` which shows for a range request of 0-100:

```
onNext: length: 0
onComplete: end
onNext: length: 101
writing: 101
onComplete: end
```
I  was wondering why the onComplete method is called after the first empty chunk is received. I thought this would inevitable cause issues, because the stream is ended multiple times (but probably I am just using it in a way should not be using it which causes this)

The second issue regarding headers:
Currently it looks like the CompletableFuture provides a reference to the vertx httpServerRequest I am trying to write to (the one I provided in the constructor). There seems to be no way to get the response that was returned from s3.

To work around that I simply added a getter to the `VertxAsyncResponseTransformer`

```
    public ResponseT getResponse() {
        return response;
    }
```

This would allow to access the s3 response. However, when the handler of the completableFuture is called, the `end()` method on the stream already has been called and setting headers simply has no effect. I thought it probably would be a good idea to skip calling `stream.end();` in the `onComplete()` method, however that causes everything to hang (I am currently not sure why...). It probably might be a good idea to manually call `stream.end()` manually from within the completableFuture callback, so we still can modify header etc of the request as needed, but right now I am not sure what is going on...

**Comment by st-h** [comment]
@aesteve 
Sorry about all the noise, but I think I ended up with something that works now:

I pretty much just added the handler I mentioned above (and removed the getter I added). This is my `AsyncResponseTransformer` now:

```
package io.reactiverse.awssdk.converters;

import io.reactiverse.awssdk.reactivestreams.WriteStreamSubscriber;
import io.vertx.core.Handler;
import io.vertx.core.buffer.Buffer;
import io.vertx.core.streams.WriteStream;
import software.amazon.awssdk.core.async.AsyncResponseTransformer;
import software.amazon.awssdk.core.async.SdkPublisher;

import java.nio.ByteBuffer;
import java.util.concurrent.CompletableFuture;

public class VertxAsyncResponseTransformer<ResponseT> implements AsyncResponseTransformer<ResponseT, WriteStream<Buffer>> {

    private volatile CompletableFuture<WriteStream<Buffer>> cf;
    private volatile ResponseT response;
    private volatile WriteStream<Buffer> writeStream;

    private Handler<ResponseT> responseHandler;

    public VertxAsyncResponseTransformer(WriteStream<Buffer> ws) {
        this.writeStream = ws;
    }

    @Override
    public CompletableFuture<WriteStream<Buffer>> prepare() {
        cf = new CompletableFuture<>();
        return cf;
    }

    @Override
    public void onResponse(ResponseT response) {
        this.response = response;
        if (this.responseHandler != null) {
            responseHandler.handle(response);
        }
    }

    @Override
    public void onStream(SdkPublisher<ByteBuffer> publisher) {
        publisher.subscribe(new WriteStreamSubscriber<>(writeStream, cf));
    }

    @Override
    public void exceptionOccurred(Throwable error) {
        cf.completeExceptionally(error);
    }

    public VertxAsyncResponseTransformer<ResponseT> setResponseHandler(Handler<ResponseT> handler) {
        this.responseHandler = handler;
        return this;
    }
}
```


Now you can do things like:

```
httpServerResponse.setChunked(true)

VertxAsyncResponseTransformer transformer = new VertxAsyncResponseTransformer<>(httpServerResponse)

transformer.setResponseHandler({ GetObjectResponse response ->
    MultiMap headers = httpServerResponse.headers()
    
    headers.set(HttpHeaders.ACCEPT_RANGES, 'bytes')
    
    Map<String, List<String>> s3Headers = response.sdkHttpResponse().headers()
    List<String> contentRanges = s3Headers.get('x-amz-content-range')
    if (contentRanges?.size() > 0) {
        headers.set(HttpHeaders.CONTENT_RANGE, contentRanges)
    }
})

s3.getObject(GetObjectRequest.builder()
                .bucket(bucket)
                .key(version.id.toString())
                .range(range)
                .build() as GetObjectRequest,
             transformer).thenAccept({ HttpServerResponse response ->

                // all done here...
});
```

Would this be ok with you? I can submit a new PR if this makes it easier for you (but I really just added the responseHandler)

**Comment by aesteve** [comment]
Hello.

So you need to hook into AWS SDK's `onResponse`. Didn't think about that but I think it can make sense, even though it adds a bit of complexity.

I added it to the PR.

**Comment by st-h** [comment]
yeah, pretty much. If there is a better way, I would be happy to go with that, but it's pretty much the only place where we seem to be able set headers that we get from the response from s3.

Otherwise, thanks a lot again for taking care of this. I just tried your update and it works great.
