### ISSUE TITLE
Compatible with Vert.x 3.7.1?

### ISSUE THREAD

**Issue by betrcode** [reactiverse/aws-sdk#38]
I am looking into using this library. 
I saw the compatibility matrix, but wanted to ask anyway: Is this library compatible with Vert.x 3.7.1?

**Comment by aesteve** [comment]
We started working on it long after Vert.x 3.7.1 was released.
I did not try to use it together with Vert.x 3.7.1 though, maybe it's wort the try?

Just include this lib in your build, while excluding vertx-core as transitive dependency. (`exclude(...)` in Gradle, for instance).

No guarantee, of course, but it **could** work.

**Comment by aesteve** [comment]
I'm closing anyway, since the official answer would be "Sorry, but no :( ".
Don't hesitate to try, though.
