### ISSUE TITLE
plans for 0.4.0 release?

### ISSUE THREAD

**Issue by st-h** [reactiverse/aws-sdk#39]
Hi there, 

are there any plans for a 0.4.0 release, which will make the changes from https://github.com/reactiverse/aws-sdk/commit/390b42a9c316cc6f94980d7a8ed9cf97ba2bfad1 available in an official release?

**Comment by aesteve** [comment]
Hello.

From what I'm seeing, it looks available: https://search.maven.org/search?q=g:io.reactiverse%20AND%20a:aws-sdk

Are you having some trouble downloading it?

**Comment by st-h** [comment]
Ah, thanks for the reply. I checked this page: https://search.maven.org/search?q=a:vertx-aws-sdk which is linked in the README.md. The docs mention the same artifact: https://reactiverse.io/aws-sdk/

> implementation("io.reactiverse:vertx-aws-sdk:0.3.0")

```
<dependency>
    <groupId>io.reactiverse</groupId>
    <artifactId>vertx-aws-sdk</artifactId>
    <version>0.3.0</version>
</dependency>
```

So is `io.reactiverse:aws-sdk` the correct artifact? I think I remember coming along a PR to rename it to vertx-aws-sdk a while ago.

**Comment by LouizFC** [comment]
Greetings

@aesteve  is `aws-sdk` a new official coordinate or a typo? I need to know so I can whitelist it on my server.

Thank very much for the effort put in this library

**Comment by aesteve** [comment]
@vietj we discussed this a long time ago, I guess we agreed it was OK? Could you confirm please?

**Comment by aesteve** [comment]
Currently working on a 0..5.0 release with Vert.x 3.9.0.

I'll keep you updated.

**Comment by aesteve** [comment]
https://repo1.maven.org/maven2/io/reactiverse/aws-sdk/0.5.0/
