### ISSUE TITLE
Consider exposing Vert.x HttpClientOptions

### ISSUE THREAD

**Issue by oxsdd** [reactiverse/aws-sdk#46]
My particular situation required supporting a proxy server, so I forked and hard coded the required additional `ProxyOptions` in the `VertxNioAsyncHttpClient`, where the Vert.x `HttpClient` is created.

It would perhaps be beneficial to support passing Vert.x `HttpClientOptions` as an optional parameter in the `VertSdkClient.withVertx` call?

**Comment by aesteve** [comment]
Good point thank you.

**Comment by aesteve** [comment]
You should be able to do so in 0.6.0, thanks again for the report.

**Comment by oxsdd** [comment]
Great, thank you!
