### ISSUE TITLE
Support the most current version of the AWS SDK

### ISSUE THREAD

**Issue by chris-brace** [reactiverse/aws-sdk#57]
[2.17.115](https://mvnrepository.com/artifact/software.amazon.awssdk/aws-core/2.17.115) has resolved several CVEs that are marked on [2.15.45](https://mvnrepository.com/artifact/software.amazon.awssdk/aws-core/2.15.45). Is there an easy way i can prove to myself and the maintainers that updating to this does not break aws-sdk? If so I will make a PR against this repo to update the README

**Comment by aesteve** [comment]
Yes, file a PR and if the CI passes that's OK.
You can also run the test locally with docker+localstack, I think the README indicates the correct options.

**Comment by aesteve** [comment]
The doc for running the tests is in the Contribution section of the README: https://github.com/reactiverse/aws-sdk#contributing

Thanks a lot for looking into that issue.
Hopefully it's gonna be compatible and the migration will be easy. If so, you can even consider changing the Vert.x version, too. 

If you face any issue please let me know and I'll test on my side and help.

**Comment by aesteve** [comment]
Hey @chris-brace I finally found some time to tackle this.
Do you think you may have a chance to give: https://oss.sonatype.org/content/repositories/snapshots/io/reactiverse/aws-sdk/1.1.0-SNAPSHOT/ a try? 
Just to triple-check before promoting to 1.1.0.

Changes are here #58 but really, that's just a bump of versions and some CI changes, no code change.

**Comment by chris-brace** [comment]
Hey! I completely let this one go, sorry. Ill put time on my calendar this week to try it out!

**Comment by chris-brace** [comment]
Ok so we have, amongst other things, a test suite which does a lot of upload / download from s3 that uses vert.x's pump and the bridge from repeatable future. All of our tests passed on 1.10-SNAPSHOT with aws sdk 2.17.129. So as far as i am able, this seems to work! :D

**Comment by aesteve** [comment]
Glad to hear that!!
I'll perform the release over the week-end probably, then.

**Comment by bitkid** [comment]
has 1.1.0 ever been released?

**Comment by aesteve** [comment]
Not on Central no. Sorry about that. (I don't have the proper credentials setup to do so unfortunately from Github Actions, and am off of computer for a while for personal reasons). 
The snapshot linked above should be the exact same though.

**Comment by chris-brace** [comment]
@aesteve any update on pushing 1.1.0 to maven central? i can close this :)

**Comment by aesteve** [comment]
https://central.sonatype.com/artifact/io.reactiverse/aws-sdk/1.1.0 has been released.

I'll try to prepare a new upgrade to 2.20 (and Vert.x 4.4) when I get some free time.

Sorry it took so long.

**Comment by chris-brace** [comment]
Thats awesome, thank you! If you need any help let me know.
