### ISSUE TITLE
Version > 2.20.75 of aws-sdk will in some cases not function with the reactiverse client

### ISSUE THREAD

**Issue by mikand13** [reactiverse/aws-sdk#65]
In my case it concerns the S3 SDK.

[L39 of WriteStreamSubscriber.java](https://github.com/reactiverse/aws-sdk/blob/883755f9068ea111ba54736ba4b473d6d681eb3d/src/main/java/io/reactiverse/awssdk/reactivestreams/WriteStreamSubscriber.java#L39) crashes when calling byteBuffer.array() because the S3 SDK passes a bytebuffer that is backed by an array but is read-only.

From docs:

[ReadOnlyBufferException](https://docs.oracle.com/javase/8/docs/api/java/nio/ReadOnlyBufferException.html) - If this buffer is backed by an array but is read-only

This prevents us from upgrading beyong 2.20.75

**Comment by aesteve** [comment]
Thanks a lot for reporting this ahead of time for the migration, this helped a lot.


I was able to reproduce in #66 and published a snapshot version here: https://oss.sonatype.org/content/repositories/snapshots/io/reactiverse/aws-sdk/1.2.2-SNAPSHOT/

Would you potentially have time to try this version locally and see if this fixes everything for you (and doesn't introduce any regression, too).

Thanks again!

**Comment by mikand13** [comment]
Can do 👌

**Comment by aesteve** [comment]
Hello,

I'm not exactly sure how long snapshots are available for on Nexus (I think it might be 30 days?) but in case the link above becomes unavailable please ping me. 

Let me know if your tests are running fine so that I can release 1.2.2.

Thank you.

**Comment by mikand13** [comment]
Yeah, sorry. I'm on it, but im away from work atm. We're testing it in an underlying lib now which will go into mainline in the near future bar any issues. Seems to work fine so far, just wanted to verify with the code that experienced the issue.

**Comment by mikand13** [comment]
Seems to work just fint @aesteve . Any timeline for 1.2.2?

**Comment by aesteve** [comment]
You should be good now: https://central.sonatype.com/artifact/io.reactiverse/aws-sdk/versions

Ping me if it's not the case!
Thanks for reporting.
